---
- name: Install OpenVPN-AS Dependencies.
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ openvpn_as_dependencies }}"

# Prepare Debian for OpenVPN-AS install
- name: Add apt key. [AS-Debian]
  apt_key:
    url: https://as-repository.openvpn.net/as-repo-public.gpg
    state: present
  when:
    - ansible_os_family == "Debian"

- name: Add apt repository. [AS-Debian]
  apt_repository:
    repo: "{{ openvpn_as_repo }}"
    state: present
    filename: openvpn-as-repo.list

# Prepare RHEL/CentOS for OpenVPN-AS install.
- name: Remove openvpn-as-yum. [AS-RHEL8]
  yum:
    name: openvpn-as-yum
    state: absent
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "8"

- name: Install OpenVPN RPM. [AS-RHEL8]
  yum:
    name:
      - https://as-repository.openvpn.net/as-repo-rhel8.rpm
    state: presnt
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "8"

- name: Install OpenVPN RPM. [AS-RHEL/Centos7]
  yum:
    name:
      - https://as-repository.openvpn.net/as-repo-centos7.rpm
    state: present
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"


# Install OpenVPN-AS Package
- name: Install OpenVPN-AS Package.
  package:
    name:
      - openvpn-as
    state: present
  notify: OpenVPN-AS Login
