---
- name: Install OpenVPN-AS Dependencies.
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ openvpn_as_dependencies }}"

- name: Add apt key. [AS-Debian]
  apt_key:
    url: https://as-repository.openvpn.net/as-repo-public.gpg
    state: present
  when:
    - ansible_os_family == "Debian"

- name: Add apt repository. [AS-Debian]
  apt_repository:
    repo: "{{ openvpn_as_repo }}"
    state: present
    filename: openvpn-as-repo.list

# - name: Install openvpn package. [AS-Debian]
#   apt:
#     name: openvpn-as
#     state: present
#     update_cache: true
#   register: __as_install_apt
#   when:
#     - ansible_os_family == "Debian"

# Install AS on RHEL

- name: Remove openvpn-as-yum. [AS-RHEL8]
  yum:
    name: openvpn-as-yum
    state: absent
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "8"

- name: Install OpenVPN RPM. [AS-RHEL8]
  yum:
    name:
      - https://as-repository.openvpn.net/as-repo-rhel8.rpm
    state: presnt
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "8"

- name: Install OpenVPN RPM. [AS-RHEL/Centos7]
  yum:
    name:
      - https://as-repository.openvpn.net/as-repo-centos7.rpm
    state: present
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"

# - name: Install OpenVPN-AS Package. [AS-RHEL/Centos]
#   yum:
#     name:
#       - openvpn-as
#     state: present
#     update_cache: true
#   register: __as_install_yum
#   when:
#     - ansible_os_family == "RedHat"

- name: Install OpenVPN-AS Package.
  package:
    name:
      - openvpn-as
    state: present
  notify: OpenVPN-AS Login


# # Pull Login information After AS Install
# - name: Pull OpenVPN-AS efault Login from init log.
#   shell:
#     cmd: cat /usr/local/openvpn_as/init.log | grep 'To login'
#   register: grep_output
#   ignore_errors: true
#   changed_when: false
#   when:
#     - __as_install_yum.changed or __as_install_apt.changed

# - name: Print default Login [AS-RHEL/Centos]]
#   debug:
#     msg: "{{ inventory_hostname }}: '{{ grep_output.stdout }}'"
#   when:
#     - __as_install_yum.changed or __as_install_apt.changed
