---
- name: Remove openvpn-as-yum [AS-RHEL8]
  yum:
    name: openvpn-as-yum
    state: absent
  when:
    -  ansible_distribution_major_version == "8"

- name: Install OpenVPN RPM. [AS-RHEL8]
  yum:
    name:
      - https://as-repository.openvpn.net/as-repo-rhel8.rpm
    state: presnt
  when:
    -  ansible_distribution_major_version == "8"

- name: Install OpenVPN RPM. [AS-RHEL/Centos7]
  yum:
    name:
      - https://as-repository.openvpn.net/as-repo-centos7.rpm
    state: present
  when:
    -  ansible_distribution_major_version == "7"

- name: Install OpenVPN-AS Package. [AS-RHEL/Centos]
  yum:
    name:
      - openvpn-as
    state: present
    update_cache: yes
  register: __as_install_yum

# - name: Pull Default Login from init log [AS-RHEL/Centos]
#   shell:
#     cmd: cat /usr/local/openvpn_as/init.log | grep 'To login'
#   register: grep_output
#   ignore_errors: yes
#   changed_when: false

# - name: Print default Login [AS-RHEL/Centos]]
#   debug:
#     msg: "{{ inventory_hostname }}: '{{ grep_output.stdout }}'"
