---
# Create Server Configuration file
- name: Create/Update OpenVPN Server configuration file
  template:
    src: server.conf.j2
    dest: "{{ openvpn_config_dir }}/server/{{ openvpn_server_conf }}"
    owner: root
    mode: 0644
  notify: restart openvpn

# Handle Openvpn Server Service
- name: Enable and Start OpenVpn-Server service.
  service:
    name: openvpn-server@server
    state: started
    enabled: trus
