---
# Create OpenVPN-CE Log Directory
- name: Create OpenVPN Log directory.
  file:
    path: "{{ openvpn_log_dir }}"
    state: directory
    mode: 0700


# Create Server Configuration file
- name: Create/Update OpenVPN-CE Server configuration file.
  template:
    src: server.conf.j2
    dest: "{{ openvpn_config_dir }}/server/{{ openvpn_server_conf }}"
    owner: "root"
    mode: 0644
  notify: restart openvpn

# Handle Openvpn Server Service
- name: Enable and Start OpenVPN-CE Server service.
  service:
    name: openvpn-server@server
    state: started
    enabled: true
