---
# Create Server Configuration file
- name: Create/Update OpenVPN Server configuration file
  template:
    src: server.conf.j2
    dest: "{{ openvpn_config_dir }}/server/{{ openvpn_server_conf }}"
    owner: root
    mode: 0644
  notify: restart openvpn

# Handle Openvpn Server Service
- name: Enable and Start OpenVpn-Server service.
  service:
    name: openvpn-server@server
    state: started
    enabled: yes

# Create Client Configurations
- name: Create Clients Configuration directory.
  file:
    path: "{{ openvpn_clients_config_dir }}"
    state: directory
    mode: 700

- name: Register CA Certificae.
  slurp:
    src: "{{ openvpn_config_dir }}/server/{{ openvpn_ca_crt_name }}"
  register: "ca_cert"

- name: Register TLS Certificae.
  slurp:
    src: "{{ openvpn_config_dir }}/server/{{ openvpn_ta_key_name }}"
  register: "tls_cert"

- name: Register Client Certs.
  slurp:
    src: "{{ openvpn_clients_keys_dir }}/{{ item }}.crt"
  register: "client_certs"
  with_items: "{{ users }}"

- name: Register Client Keys
  slurp:
    src: "{{ openvpn_clients_keys_dir }}/{{ item }}.key"
  register: "client_keys"
  with_items: "{{ users }}"

- name: Create/Update OpenVPN Client configuration files.
  no_log: true
  template:
    src: client.ovpn.j2
    dest: "{{ openvpn_clients_config_dir }}/{{ item.0.item }}.ovpn"
    owner: root
    mode: 0644
  with_together:
    - "{{ client_certs.results }}"
    - "{{ client_keys.results }}"
  notify: restart openvpn

- name: Pull client connection files to localhost
  fetch:
    src: "{{ openvpn_clients_config_dir }}/{{ item }}.ovpn"
    dest: "client.ovpn"
  with_items: "{{ users }}"