---
# Create non root user for OpenVPN
- name: Create OpenVPN group.
  group:
    name: "{{ openvpn_system_group }}"
    state: present
    system: true
  when:
    - openvpn_system_group != "root"

- name: Create OpenVPN user.
  user:
    name: "{{ openvpn_system_user }}"
    groups: "{{ openvpn_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /
  when:
    - openvpn_system_group != "root"

# Install OpenVPN-CE
- name: Install OpenVPN-CE dependencies.
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ openvpn_ce_dependencies }}"

- name: Install OpenVPN-CE package.
  package:
    name: openvpn
    state: present

# Install Easy-RSA
- name: Install Easy-RSA dependencies.
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ easyrsa_dependencies }}"

- name: Install Easy-RSA package.
  package:
    name: "{{ easyrsa_package }}"
    state: present

# Set ip forwarding on in /proc and verify token value with the sysctl command
- name: Enable IP forwarding for IPV4 networks
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true
