---
- name: Install Dependencies [CE-RHEL/CentOS]
  yum:
    name:
      - epel-release
    state: present
    update_cache: true
  when: ansible_os_family == "RedHat"

- name: Install OpenVPN Package. [CE-RHEL/CentOS]
  yum:
    name:
      - openvpn
    state: present
  when: ansible_os_family == "RedHat"

- name: Install OpenVPN package. [CE-Debian]
  apt:
    name: openvpn
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

# Set ip forwarding on in /proc and verify token value with the sysctl command
- name: Enable IP forwarding for IPV4 networks
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true
