---
# Install OpenVPN Access Server (GUI with 2 client limit) if Enabled
- name: Install OpenVPN AS on RedHat/CentOS.
  import_tasks: as_rhel_install.yml
  when:
    - ansible_os_family == "RedHat"
    - install_as

- name: Install OpenVPN AS on Debian.
  import_tasks: as_debian_install.yml
  when:
    - ansible_os_family == "Debian"
    - install_as

- name: Retrieve OpenVPN AS Default Login.
  import_tasks: as_login.yml
  when:
    - install_as
    - __as_install_yum.changed or __as_install_apt.changed

# Install OpenVPN Communitiy Edition if Enabled
- name: Install OpenVPN CE on RedHat/Centos.
  import_tasks: ce_install.yml
  when:
    - not install_as

# Create CA and Server certs for OpenVPN CE
- name: Generate Certificate Configuration
  import_tasks: ce_certs.yml
  when:
    - not install_as

# - name: Build CA and Server Certificates using Easy-RSA.
#   import_tasks: ce_certs_server.yml
#   when:
#     - not install_as


# - name: Configure Clients Certificates using Easy-RSA.
#   import_tasks: ce_certs_clients.yml
#   when:
#     - not install_as


- name: Configure OpenVPN Server and Clients.
  import_tasks: ce_config.yml
  when:
    - not install_as


