---
# Include OS Specific Vars.
- name: Include Debian Specific Vars.
  include_vars:
    file: debian.yml
  when:
    - ansible_os_family == "Debian"

- name: Include RHEL/CentOS Specific Vars.
  include_vars:
    file: rhel.yml
  when:
    - ansible_os_family == "RedHat"

- name: Update apt cache.
  apt:
    update_cache: true
  when:
    - ansible_os_family == "Debian"

- name: Update yum cache.
  yum:
    update_cache: true
  when:
    - ansible_os_family == "RedHat"

# Install OpenVPN Access Server (GUI with 2 client limit) if Enabled
- name: Install OpenVPN AS.
  import_tasks: as_install.yml
  when:
    - install_as

# Install OpenVPN Community Edition (Open Source, CLI only) if Enabled
- name: Install OpenVPN CE.
  import_tasks: ce_install.yml
  when:
    - not install_as

# Create CA and Server certs for OpenVPN CE
- name: Generate CA / Server Certificate Configuration
  import_tasks: ce_certs.yml
  when:
    - not install_as

# Create OpenVPN Configuration.
- name: Configure OpenVPN Server.
  import_tasks: ce_config.yml
  when:
    - not install_as

# Create Client Certificates and Config files
- name: Configure Clients Certificates and Configuration Files.
  import_tasks: ce_clients.yml
  when:
    - not install_as
