---
#########################################
# Install OpenVPN Access Server AS      #
# Limit to 2 connections without license#
# GUI                                   #
#########################################
# Install OpenVPN Access Server (GUI with 2 client limit) if Enabled
- name: Install OpenVPN AS on RedHat/CentOS.
  import_tasks: as_install_rhel.yml
  when:
    - ansible_os_family == "RedHat"
    - install_as

- name: Install OpenVPN AS on Debian.
  import_tasks: as_install_debian.yml
  when:
    - ansible_os_family == "Debian"
    - install_as

- name: Retrieve OpenVPN AS Default Login.
  import_tasks: as_login.yml
  when:
    - install_as
    - __as_install_yum.changed or __as_install_apt.changed

#########################################
# Install OpenVPN Communitiy Edition CE #
# Open Source, CLI only                 #
#########################################
# Install OpenVPN CE if Enabled
- name: Install OpenVPN CE on RedHat/Centos.
  import_tasks: ce_install.yml
  when:
    - not install_as

# Create CA and Server certs for OpenVPN CE
- name: Generate CA / Server Certificate Configuration
  import_tasks: ce_certs.yml
  when:
    - not install_as

# Create OpenVPN Configuration.
- name: Configure OpenVPN Server.
  import_tasks: ce_config.yml
  when:
    - not install_as

# Create Client Certificates and Config files
- name: Configure Clients Certificates and Configuration Files.
  import_tasks: ce_clients.yml
  when:
    - not install_as
