---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-openvpn
      users: ["user1"]
      client_routes: ["10.0.0.0 255.255.255.0"]
      hostname: "instance"
      tags:
        - openvpn
