---
- name: Install Dependencies. [AS-Debian]
  apt:
    name:
      - ca-certificates
      - wget
      - net-tools
      - gnupg
    update_cache: yes

- name: Add apt key. [AS-Debian]
  apt_key:
    url: https://as-repository.openvpn.net/as-repo-public.gpg
    state: present

- name: Add apt repository. [AS-Debian]
  apt_repository:
    repo: deb http://as-repository.openvpn.net/as/debian {{ ansible_distribution_release }} main
    state: present
    filename: openvpn-as-repo.list

- name: Install openvpn package. [AS-Debian]
  apt:
    name: openvpn-as
    state: present
    update_cache: yes

- name: Pull Default Login from init log [AS-Debian]
  shell:
    cmd: cat /usr/local/openvpn_as/init.log | grep 'To login'
  register: grep_output
  ignore_errors: yes
  changed_when: false

- name: Print default Login [AS-Debian]
  debug:
    msg: "{{ inventory_hostname }}: '{{ grep_output.stdout }}'"

