---
# Ensure Easy-RSA is installed
- name: Install Easy-RSA package. [CE-RHEL/CentOS]
  yum:
    name: easy-rsa
    state: presnt
  when: ansible_os_family == "RedHat"

- name: Install Easy-RSA package. [CE-Debian]
  apt:
    name: easy-rsa
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

# Create Certificate Authority PKI Infrastructure
- name: Create CA directory.
  file:
    path: "{{ easyrsa_ca_dir }}"
    state: directory
    mode: 700

- name: Create CA Vars.
  template:
    src: easyrsa-ca-vars.j2
    dest: "{{ easyrsa_ca_dir }}/vars"

- name: Initialize CA PKI.
  command: "{{ easyrsa_bin }} init-pki"
  args:
    chdir: "{{ easyrsa_ca_dir }}"
    creates: "{{ easyrsa_ca_dir }}/pki"

# Build Certificate Authority
- name: Build CA.
  command: "{{ easyrsa_bin }} --batch build-ca nopass"
  args:
    chdir: "{{ easyrsa_ca_dir }}"
    creates: "{{ easyrsa_ca_dir }}/pki/private/ca.key"


# Create Server PKI Infrastructure
- name: Create Server directory.
  file:
    path: "{{ easyrsa_server_dir }}"
    state: directory
    mode: 700

- name: Initialize Server PKI.
  command: "{{ easyrsa_bin }} init-pki"
  args:
    chdir: "{{ easyrsa_server_dir }}"
    creates: "{{ easyrsa_server_dir }}/pki"

# Generate Signing request for server and TLS Key
- name: Create Server Request and Key.
  command: "{{ easyrsa_bin }} --batch --req-cn={{ hostname }} gen-req {{ hostname }} nopass"
  args:
    chdir: "{{ easyrsa_server_dir }}"
    creates: "{{ easyrsa_server_dir }}/pki/private/{{ hostname }}.key"

# Use CA to mport and Sign Server request
- name: Import Server Request.
  command: "{{ easyrsa_bin }} --batch import-req {{ easyrsa_server_dir }}/pki/reqs/{{ hostname }}.req {{ hostname }}"
  args:
    chdir: "{{ easyrsa_ca_dir }}"
    creates: "{{ easyrsa_ca_dir }}/pki/reqs/{{ hostname }}.req"

- name: Sign Server Request.
  command: "{{ easyrsa_bin }} --batch sign-req server {{ hostname }}"
  args:
    chdir: "{{ easyrsa_ca_dir }}"
    creates: "{{ easyrsa_ca_dir }}/pki/issued/{{ hostname }}.crt"

# Create TLS Key
- name: Create TLS Key.
  command: "openvpn --genkey secret {{ openvpn_ta_key_name }}"
  args:
    chdir: "{{ easyrsa_server_dir }}"
    creates: "{{ easyrsa_server_dir }}/{{ openvpn_ta_key_name }}"


# Move Certificates / Key to OpenVPN Directories
- name: Move CA Certificate to OpenVPN Server directory.
  copy:
    remote_src: true
    src: "{{ easyrsa_ca_dir }}/pki/ca.crt"
    dest: "{{ openvpn_config_dir }}/server/{{ openvpn_ca_crt_name }}"

- name: Move Server key to OpenVPN Server directory.
  copy:
    remote_src: true
    src: "{{ easyrsa_server_dir }}/pki/private/{{ hostname }}.key"
    dest: "{{ openvpn_config_dir }}/server/{{ openvpn_server_key_name }}"

- name: Move signed Server Certificate to OpenVPN directory.
  copy:
    remote_src: true
    src: "{{ easyrsa_ca_dir }}/pki/issued/{{ hostname }}.crt"
    dest: "{{ openvpn_config_dir }}/server/{{ openvpn_server_crt_name }}"

- name: Move TLS Certificate to OpenVPN Server directory.
  copy:
    remote_src: true
    src: "{{ easyrsa_server_dir }}/{{ openvpn_ta_key_name }}"
    dest: "{{ openvpn_config_dir }}/server/{{ openvpn_ta_key_name }}"
