---
# Ensure Easy-RSA is installed
- name: Install Easy-RSA package. [CE-RHEL/CentOS]
  yum:
    name:
      - easy-rsa
    state: presnt
  when: ansible_os_family == "RedHat"

- name: Install Easy-RSA package. [CE-Debian]
  apt:
    name: easy-rsa
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

# Create PKI infrastucture
- name: Create Clients PKI directory.
  file:
    path: "{{ easyrsa_clients_dir }}"
    state: directory
    mode: 700

- name: Initialize Clients PKI.
  command: "{{ easyrsa_bin }} init-pki"
  args:
    chdir: "{{ easyrsa_clients_dir }}"
    creates: "{{ easyrsa_clients_dir }}/pki"

# Create Signing requests per user
- name: Create Clients Request and Key.
  command: "{{ easyrsa_bin }} --batch --req-cn={{ item }} gen-req {{ item }} nopass"
  args:
    chdir: "{{ easyrsa_clients_dir }}"
    creates: "{{ easyrsa_clients_dir }}/pki/private/{{ item }}.key"
  with_items: "{{ users }}"

# Import and Sign Clients request
- name: Import Clients Request.
  command: "{{ easyrsa_bin }} --batch import-req {{ easyrsa_clients_dir }}/pki/reqs/{{ item }}.req {{ item }}"
  args:
    chdir: "{{ easyrsa_ca_dir }}"
    creates: "{{ easyrsa_ca_dir }}/pki/reqs/{{ item }}.req"
  with_items: "{{ users }}"

- name: Sign Client Request.
  command: "{{ easyrsa_bin }} --batch sign-req client {{ item }}"
  args:
    chdir: "{{ easyrsa_ca_dir }}"
    creates: "{{ easyrsa_ca_dir }}/pki/issued/{{ item }}.crt"
  with_items: "{{ users }}"

# Move certificates / Key to OpenVPN Directory
- name: Create Clients Config Keys directory.
  file:
    path: "{{ openvpn_clients_keys_dir }}"
    state: directory
    mode: 700

- name: Move Signed Clients Certificate to OpenVPN Client directory.
  copy:
    remote_src: true
    src: "{{ easyrsa_ca_dir }}/pki/issued/{{ item }}.crt"
    dest: "{{ openvpn_clients_keys_dir }}/{{ item }}.crt"
  with_items: "{{ users }}"

- name: Move Clients Keys to OpenVPN Client directory.
  copy:
    remote_src: true
    src: "{{ easyrsa_clients_dir }}/pki/private/{{ item }}.key"
    dest: "{{ openvpn_clients_keys_dir }}/{{ item }}.key"
  with_items: "{{ users }}"

- name: Move CA Certificate to OpenVPN Client directory.
  copy:
    remote_src: true
    src: "{{ easyrsa_ca_dir }}/pki/ca.crt"
    dest: "{{ openvpn_clients_keys_dir }}/{{ openvpn_ca_crt_name }}"

- name: Move TLS Certificate to OpenVPN Client directory.
  copy:
    remote_src: true
    src: "{{ easyrsa_server_dir }}/{{ openvpn_ta_key_name }}"
    dest: "{{ openvpn_clients_keys_dir }}/{{ openvpn_ta_key_name }}"