# Set ip forwarding on in /proc and verify token value with the sysctl command
- name: Enable IP forwarding for IPV4 networks
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
